#!/bin/bash
echo "enter the filename : "
read fname
if [ -f "$fname" ]
then
echo "file exists"
echo "number of lines : "
wc -l $fname
echo "number of words : "
wc -w $fname
echo "number of characters : "
wc -c $fname

else
echo "no such file exists "
fi

output -
bmsce@DESKTOP-LSN1E53:~$ sh count.sh
enter the filename :
emp.lst
file exists
number of lines :
4 emp.lst
number of words :
16 emp.lst
number of characters :
128 emp.lst
